### ISSUE TITLE
Gateway error after deploying to vercel according to your method

### ISSUE THREAD

**Issue by MyProgramsForTT** [hocgin/vercel-chatgpt#1]
Error: 
This Serverless Function has timed out.

Your connection is working correctly.

Vercel is working correctly.

504: GATEWAY_TIMEOUT
Code: FUNCTION_INVOCATION_TIMEOUT
ID: fra1::kd4xt-1670737355213-83028fefdf2f

Do you need any settings besides adding token?

**Comment by hocgin** [comment]
Timeout is Vercel Serverless Function has restricted request time. 
You can check if the chatgpt response is too slow.
see: https://vercel.com/docs/concepts/limits/overview

超时是 Vercel Serverless Function 有限制请求时间。可以查看一下是否 chatgpt 响应太慢了。
